### ISSUE TITLE
SessionStateHandler should use LaravelSessionStore not SessionStore

### ISSUE THREAD

**Issue by afreakk** [auth0/laravel-auth0#125]
### Description

Currently state validation uses $_SESSION to save state, not laravel Session::get/put.
Which wont work when using multiple servers and loadbalancer.
(Unless you define your own SessionHandler using session_set_save_handler, but that is redundant in laravel, because laravel has its own solution: https://laravel.com/docs/5.8/session)

And you already utilize laravel session for store https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Auth0Service.php#L26   
But not for stateHandler...   

You would also have to do something about the auth0->login flow, for laravel session to work, because it uses `exit;` here: https://github.com/auth0/auth0-PHP/blob/master/src/Auth0.php#L444
Because laravel Session::Save wont be run if you break the normal laravel request flow.

**Comment by joshcanhelp** [comment]
@afreakk Thank you for the report here. I agree and will make sure this is on our roadmap for a future release.

**Comment by nstapelbroek** [comment]
Hey 👋,

I wanted to use a passwordless login but there is currently no way to acquire a custom `issue` and pass it to Lock.js to assure it doesn't cause a mismatch on callback later. 

Although this issue is not directly related, I was thinking about fixing this by instantiating a SessionStateHandler in the Laravel Serviceprovider and passing it to the Auth0Service. That should also take care of using the LaravelSessionStore in the provider.

@joshcanhelp let me know if this approach makes sense. I'll see if I can get this into a PR :).

**Comment by joshcanhelp** [comment]
Fixed in #135
