### ISSUE TITLE
Authenticate as a Laravel API user using the Auth0 token

### ISSUE THREAD

**Issue by roasted-toast** [auth0/laravel-auth0#129]
I'm a little bit confused on what would be the best approach to achieve a simple "2 way" user Authentication using the given token.

### The context
I've a Vue.js SPA that uses Auth0 to authenticate users. It works as intended, users can login and logout, token is stored in my Vuex store, expires correctly.

Beside that, I've a custom local Laravel API (JWT/Dingo API) that uses the laravel-auth0 package to check for the JWT token using the Auth0 API.
It works great, I can protect my API endpoints using the `jwt` middleware.

### My question
Now that my users can login to the SPA with Auth0 (using Facebook or Google), and access my custom Laravel API endpoints using the JWT tokenId, how can I register them in my Laravel APP?

This custom API needs the use of the `Auth` facade.

I've tried to implement [this part](https://auth0.com/docs/quickstart/webapp/laravel#optional-custom-user-handling) of the quick start, but unfortunately, I'm still confused on how I should use the `CustomUserRepository` class.

How am I supposed to login/logout to/from my Laravel API in the background using the token ? Do I have to call the `getUserByDecodedJWT` from a custom endpoint with the OpenID Object as a parameter when Auth0 return a successful authentication?

And then, how can I retrieve he logged-in user in my API logic?

Thanks!

**Comment by roasted-toast** [comment]
I've opened an issue when this should be a thread on the community site. My apologizes.
Anyways, I've found a solution by myself: using the auth0 driver was the key (my app was still using the jwt driver provided by the dingo api package)!

**Comment by krthush** [comment]
I'm just following up on this because I'm still a bit lost - I actually have made a community post about this here with more details: https://community.auth0.com/t/native-app-laravel-api-both-with-auth0/32299

So how exactly do I use the token + user credentials from a Vue frontend (in my case its actually Nativescript-Vue), to call a Laravel API - where the Laravel API is able to authenicate and identify the user before sending them back a JSON response.

**Comment by joshcanhelp** [comment]
I'll answer on your Community thread but it sounds like you're on the right track!

**Comment by egdavid** [comment]
@krthush what your Vue app should do is to send a request to your Laravel API, get a response, store the JWTToken (access_token) inside an httpOnly cookie, use this token as a parameter (typically in the Authorization header using the Bearer schema) and use the refresh token whenever it's needed.

**Comment by krthush** [comment]
@egdavid So I sort of managed to do this, but my problem is that when I call the api to any of my standard Laravel routes they just redirect to the login in page...

![image](https://user-images.githubusercontent.com/33790334/66856033-3ecb3a00-ef7c-11e9-8dc4-44170b91729c.png)

**Comment by krthush** [comment]
Managed to find a solution: https://community.auth0.com/t/native-app-laravel-api-both-with-auth0/32299/5?u=thush

Thanks @egdavid  @joshcanhelp !

**Comment by joshcanhelp** [comment]
I'm just circling back to this now and will post in the Community thread in just a few minutes but want to address what @egdavid said. 

A lot of the guidance I can provide depends entirely on your architecture. If you're building a Vue SPA and it's consuming an API only meant for that SPA (same domain), then your architecture can be pretty straightforward. You would use this package to log in and then use whatever Laravel has built-in for API authentication (or even cookies). I wrote out a detailed explanation about this in [another Community thread earlier this year](https://community.auth0.com/t/api-route-api-authentication-not-working-in-laravel/20201/6?u=josh.cunningham).

> What your Vue app should do is to send a request to your Laravel API to authenticate the user the first time

You wouldn't be authenticating a user via an API. 

> store the JWTToken (access_token) inside an httpOnly cookie

`httpOnly` cookies cannot be accessed in JS so that's not possible.
