### ISSUE TITLE
Minor update 5.6 included a breaking change

### ISSUE THREAD

**Issue by b12f** [auth0/laravel-auth0#155]
### Description

The following commit introduced a change that was breaking for our setup:

https://github.com/auth0/laravel-auth0/commit/2f246563689ef58862b1c5dc04fd77a7a39e75c3#diff-e168400503eeb1bee592a85539a386e7L83

We are currently calling the Auth0/Login package like this:

```
        app('auth0')->login(null, null, [
            'scope'     => 'openid email email_verified',
            'prompt'    => 'none',
        ], 'code');
```

This works fine in 5.5.1, where the user gets redirected if they are not authenticated. However, the changed code _returns_ the url that the user should be redirected to, which means that from 5.5.1 to 5.6.0 there was a breaking change introduced that fails silently. I'm not sure if we were using the library incorrectly, but this feels like it should have been a major version bump.

Since 5.6.0 is already out in the wild, I'm guessing it stands as it is, but I'm posting this issue anyway so people googling will find what they're looking for.

**Comment by joshcanhelp** [comment]
@b12f - Apologies for this. It was definitely not our intention to break anyone on a minor release. 

It looks like the issue here is that your controller is not returning anything. If you put a `return` in front of that statement, you should be back in business. Because our [quickstart](https://auth0.com/docs/quickstart/webapp/laravel#set-up-routes) assume that the controller is returning (and typically should be, in my experience) and the test apps we were all using do the same, this potential break was not picked up. 

Here's what should fix the issue for you. Note that your call to `login()` has a 4th parameter that's not defined in that method (`'code'` is the default response mode so it wouldn't be necessary):

```php
class Auth0IndexController extends Controller
{

    public function login()
    {
        $authorize_params = [
            'scope' => 'openid email email_verified',
            'prompt'    => 'none',
        ];

        return \App::make('auth0')->login(null, null, $authorize_params);
    }
    // ...
}
```

Again, apologies for the breakage. This was a public API change, regardless of our assumptions. I'll make a note of your usage to make sure we don't make this mistake in the future.
