### ISSUE TITLE
TypeError in Auth0UserRepository

### ISSUE THREAD

**Issue by homeoftheunits** [auth0/laravel-auth0#198]
Hi,

I want to use Auth0 with my Laravel 8 installation. I use an new Laravel8 installation and following your instructions on https://auth0.com/docs/quickstart/webapp/laravel#optional-custom-user-handling

The redirect to the Auth0 Login Page works, when i register a user and the callback URL is called, i got the error in my application:
`
TypeError
Argument 1 passed to Auth0\Login\Repository\Auth0UserRepository::getUserByUserInfo() must be of the type array, null given, called in /app/vendor/auth0/login/src/controllers/Auth0Controller.php on line 37
`

What do i wrong?

Cheers
Ralf

**Comment by evansims** [comment]
Hi Ralf! 👋 Very sorry to hear you're having an issue with this. Assuming you're using the latest 6.1 release, which version of PHP are you on? Would it be possible to share this code in a repo for me to take a look? Understandable if not but it would help in debugging this.

You might also take a look at [our Laravel quickstart app](https://github.com/auth0-samples/auth0-laravel-php-web-app) which is setup to use custom user handling out of the box, just to see if perhaps something is out of sync with your code, or quite possibly our documentation (I'm in the process of updating all our PHP docs at the moment.)

**Comment by homeoftheunits** [comment]
Hi,

i push the code here: https://github.com/homeoftheunits/auth0

As i say, i follow the path on your Quickstart, but maybe i do things wrong. My PHP Version is 7.3

Cheers
Ralf

**Comment by evansims** [comment]
Hey again Ralf! 👋  Did a clone of that and looked things over, thanks for putting that online for me.

I'm noticing a few missing files/steps outlined from the quickstart which is probably what's causing your issue here. Since you don't appear to have much custom code going here, I'd encourage you to try cloning [our Laravel quickstart app directly](https://github.com/auth0-samples/auth0-laravel-php-web-app) and starting from that as a base, as it should work out of the box for you and save you some effort.

If you continue to have issues feel free to reply here and we'll keep working on getting things working for you

**Comment by endu-Sean** [comment]
I am having the exact same issue, I have tried to copy over the relevant files from the quickstart but with no luck.

**Comment by evansims** [comment]
Hi @endu-Sean 👋 Sorry to hear that. Could you try cloning [the quickstart app directly](https://github.com/auth0-samples/auth0-laravel-php-web-app) and seeing if that works for you? I may need to update that quickstart's documentation if we've overlooked a step somewhere.

**Comment by endu-Sean** [comment]
I also raised this issue here: https://community.auth0.com/t/laravel-vuexy-vue-jwt/53514?u=seana

Because I am using Vuexy I downloaded the quickstart yesterday and copied the relevant files over to my application with no luck.

I am really at a loss here as I do not know if i should be using laravel quickstart, vue quickstart or the one that comes implimented already into my application from Vuexy so I have tried all of them.

I am always able to authenticate, the issue comes when saving the user details to the database.

Thanks in advance for your help.

**Comment by diannall** [comment]
Hi, did you ever get this solved @endu-Sean?
I've gone through the install process twice and also tried the quickstart app. I keep getting the following:

`Argument 1 passed to Auth0\Login\Repository\Auth0UserRepository::getUserByUserInfo() must be of the type array, null given, called in xxx/vendor/auth0/login/src/controllers/Auth0Controller.php on line 37`

**Comment by shawndreck** [comment]
I think the issue stems from the method signature as defined in the ` Auth0\Login\Contract\Auth0UserRepository`. The method is defined as  `public function getUserByUserInfo(array $userInfo) : Authenticatable;` simply meaning that only array types are accepted. However when you access `/auth0/callback` (GET request) , the value of variable passed will be empty/null and PHP interpreter will complain about this. 

A simple fix was to override the `Auth0\Login\Auth0Controller` and in the callback method, include a check for null first before passing it to the `getUserByUserInfo`. Here is a sample of the callback method as in the Auth0Controller:

```public function callback()
    {
        // Get a handle of the Auth0 service (we don't know if it has an alias)
        $service = app()->make('auth0');

        // Try to get the user information
        $profile = $service->getUser();

        // Get the user related to the profile
        $auth0User = null;

        if ($profile) {
            $auth0User = $this->userRepository->getUserByUserInfo($profile);
        }

        if ($auth0User) {
            // If we have a user, we are going to log them in, but if
            // there is an onLogin defined we need to allow the Laravel developer
            // to implement the user as they want an also let them store it.
            if ($service->hasOnLogin()) {
                $user = $service->callOnLogin($auth0User);
            } else {
                // If not, the user will be fine
                $user = $auth0User;
            }

            Auth::login($user, $service->rememberUser());
        }

        return Redirect::intended('/');
    }
    ```
    
    Don't forget to update the `routes/web.php` to the custom Auth0Controller. I hope it helps
