### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by digitalsounds** [auth0/laravel-auth0#202]
### Describe the problem you'd like to have solved
Enable support for PHP 8.0

### Describe the ideal solution

Changing composer.json dependency and upgrading related packages e.g. auth0/auth0-php

## Alternatives and current work-arounds

None. Adding the --ignore-platform-reqs although will let you install the package, will break in php 8.0 due to various changes in the PHP version itself.

### Additional information, if any

There is a similar ticket against the auth0/auth0-php dependency here: https://github.com/auth0/auth0-PHP/issues/469

**Comment by evansims** [comment]
Hi @digitalsounds 👋  Thanks for raising this! As you mentioned, our SDK upstream dependency has a pending PR ([#467](https://github.com/auth0/auth0-PHP/pull/467)) to add PHP 8 compatibility, and once that is merged and released I can merge the PR for the Laravel SDK (#200) which will complete our support for PHP 8.

Due to the holidays our internal review process is going a bit slower than usual, but I'm hoping we'll have it sorted out shortly. I'll update this thread when I have news to share.

I'll pin this issue since I'm sure it is of importance to many checking in here

**Comment by la-roberto** [comment]
Hi there! Thanks for everything that you guys are doing. Any update on this or on the PR side?

**Comment by evansims** [comment]
Heya @la-roberto 👋 Thanks! Just waiting on an internal review to finish and I can get it merged and shipped. Shouldn't be too much longer on this.

**Comment by evansims** [comment]
Thanks for your patience! [6.2.0 is now available with PHP 8.0 support](https://github.com/auth0/laravel-auth0/releases/tag/6.2.0)  🚀
