### ISSUE TITLE
If there is no token, it dies without throwing an exception

### ISSUE THREAD

**Issue by SasSam** [auth0/laravel-auth0#226]
### SDK Version

7.9

### PHP Version

PHP 7.4

### Composer Version

2.x

### What happened?

If the token is null, the SDK doesn't throw `InvalidTokenException` but dies miserably with error 500.

Error message:
`TypeError: Argument 1 passed to Auth0\SDK\Helpers\Tokens\TokenVerifier::verify() must be of the type string, null given, called in [...]\vendor\auth0\login\src\Auth0\Login\Auth0Service.php on line 231 in file [...]\vendor\auth0\auth0-php\src\Helpers\Tokens\TokenVerifier.php on line 86`

Reason: 
The `verify()` method (in `auth0-php\src\Helpers\Tokens\TokenVerifier.php`) has a type definition for `$token` which is a string. Null is not a string. Hence, it never reaches the condition where it wants to check if it's empty or not.

```
    public function verify(string $token, array $options = []): array
    {
        if (empty($token)) {
            throw new InvalidTokenException('ID token is required but missing');
        }

```

### How can we reproduce this issue?

Call the `verify()` without a token.

**Comment by evansims** [comment]
Can you tell me a little more about the circumstances in which you're seeing this issue appear?

I am trying to diagnose under what conditions this could occur. It would appear that [`retrieveByCredentials` should handle cases](https://github.com/auth0/laravel-auth0/blob/3ba11791a5ac81391b2451c24a1b54c39ac5eb97/src/Auth0/Login/Auth0UserProvider.php#L52) where a token isn't provided, before `getUserByDecodedJWT` is invoked, which is what calls `verify` on the SDK.

**Comment by SasSam** [comment]
hi @evansims ,

The easiest way to replicate this is if you follow this blog post's steps:
https://auth0.com/blog/build-and-secure-laravel-api/#Secure-your-Laravel-API

Code repo:
https://github.com/auth0-blog/laravel-api-auth

I've tried with the latest Laravel.

**Comment by evansims** [comment]
Ahh, yes, I see the issue you're pointing out there. So, to be honest, this is more of an oversight in the blog post than it is the SDK itself: it circumvents the functions that check these values in the SDK itself to provide a simpler demonstration, understandably, but it skips a few things in the process. I'll be working with our Developer Relations team on the next iterations of these posts, and we'll address those better in the future.

The underlying issue is: There should be a check on that `handle()` function in the blog post to check if a token is actually present to handle, before `decodeJWT` is fired off. That said, again, this is more of a flaw in the usage than the SDK itself. The next major of this plugin will be more proactive in its processing to address edge cases like this.

To address this in the example, though, simply check if the string is present and valid within your application logic before passing it off to the `decodeJWT. method, and you'll be fine.

**Comment by heyharmon** [comment]
Ran into this too. Set $accessToken to a string if not retrieved from request, like this:

$accessToken  = $request->bearerToken() ?? '';
