### ISSUE TITLE
Incorrect logout redirect link

### ISSUE THREAD

**Issue by nsaumini** [auth0/laravel-auth0#260]
### SDK Version

7.0

### PHP Version

PHP 8.0

### Composer Version

2.x

### What happened?

I followed the instructions in [Laravel 9 Beta guide](https://auth0.com/docs/quickstart/webapp/laravel-beta/). The login works, but when I click logout it displays below error page. 

As per the error details, it is redirecting to `/auth0/callback` but I expected to redirect welcome page `/`. I don't see this url is configurable.

<img width="1051" alt="Screenshot 2022-02-15 at 21 28 49" src="https://user-images.githubusercontent.com/12414016/154152545-cc8d41d2-10b8-4162-a7c7-28a69609b235.png">

### How can we reproduce this issue?

Follow the [Laravel 9 Beta guide](https://auth0.com/docs/quickstart/webapp/laravel-beta/) documentation

**Comment by evansims** [comment]
Hey @nsaumini 👋 Thanks for your report.

Good catch, that should be configurable (although it will at present work if you set your callback as an Allowed Logout URL in your Auth0 application settings! It will bounce you back to your index route from the callback.) I'll prepare a fix so that it will redirect to the configured '/' route instead, or whatever is otherwise configured as your auth0.routes.home.
