### ISSUE TITLE
Auth0\SDK\Configuration\SdkConfiguration::setCookiePath(): Argument #1 ($cookiePath) must be of type string, null given

### ISSUE THREAD

**Issue by untitledpng** [auth0/laravel-auth0#323]
### SDK Version

7.2

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

All the pages now display the following error:
```
Auth0\SDK\Configuration\SdkConfiguration::setCookiePath(): Argument #1 ($cookiePath) must be of type string, null given, called in /vendor/auth0/auth0-php/src/Mixins/ConfigurableMixin.php on line 29
```

I have two clean Laravel Jetstream with Livewire installations (exact package versions below) with the only difference between these two installations is that project A was last updated a month ago and project B (broken) today.

Project A works until I update laravel to the latest version, which suggests that this package is not compatible with the latest Laravel (jetstream) anymore.

Project A composer versions:
```
auth0/login: 7.2.1
laravel/framework: 9.23.0
laravel/jetstream: 2.10.3
livewire/livewire: 2.10.6
```

Project B composer versions:
```
auth0/login: 7.2.1
laravel/framework: 9.36.3
laravel/jetstream: 2.12.3
livewire/livewire: 2.10.7
```

### How can we reproduce this issue?

Just install a clean version of laravel via the command:
`laravel new --jet` and select livewire.

After that just follow your own instructions of the installation (README.md of this repo)

**Comment by tjmahaffey** [comment]
I can confirm this same issue. 

auth0/login: 7.2.1
auth0/auth0-php: 8.3.2
laravel/framework: 9.36.3
(No jetstream, no livewire.)

**Comment by evansims** [comment]
Hi @untitledpng and @tjmahaffey 👋 Thanks for letting me know, and apologies for the issue.

I've just released 7.2.2 which should address the issue. You may need to regenerate your Auth0 config (`php artisan vendor:publish --tag=auth0-config`) to address the `cookiePath` error fully. Thanks for your help in troubleshooting this.

**Comment by untitledpng** [comment]
Hi @evansims,

This has resolved the issue, thank you for picking this up so quickly!

**Comment by watercayman** [comment]
Hi @evansims ,

Had what appears to be a related problem upon upgrade from 7.0 to 7.2 on a standard production build (no livewire/jetstream) Laravel v 9.36.  

All pages failed and pushed error: **Validation of "cookiePath" was unsuccessful**

I tested same app on vagrant, docker, and linux and all failed with same error.

I downgraded to 7.0 and tested on all three boxes - all successfully loaded without error.

I finally found this page, but would not have thought a config change to have been necessary, as I have already published that file.  After re-installing to 7.2 and then deleting my current config file and re-publishing, **I can confirm success**.

However, if this error reproduces on similar builds, it might be helpful in future update versions to not have to force users to change config settings due to a package update.
