### ISSUE TITLE
Decoded response from API call differs from decoded JWT user

### ISSUE THREAD

**Issue by thijsvdanker** [auth0/laravel-auth0#33]
Is there a (good) reason why the response body from the API request is converted into an associative array? (true parameter in the `return json_decode($body, true);` [here](https://github.com/auth0/auth0-PHP/blob/master/src/API/Helpers/RequestBuilder.php#L118)

When using the Laravel [Auth0JWTMiddleware](https://github.com/auth0/laravel-auth0/blob/master/src/Auth0/Login/Middleware/Auth0JWTMiddleware.php) to decode a JWT token into a user, the body is not converted.

This causes issues because you now have to check if the `app_metadata` and its data is an array or an object.

For consistency reasons I think it would be good to either not convert it to an associative array in the SDK, or do convert it as well in the Auth0UserRepository.

**Comment by glena** [comment]
It is to be consistent with the user returned by auth0-php when using it for authentication (https://github.com/adoy/PHP-OAuth2/blob/master/src/OAuth2/Client.php#L475) but you are right, it sucks because of `json_decode` not being consistent.

Anyway, I think it would be weird receiving a stdClass using the middleware and an asoc array using the other flow, right?

**Comment by cocojoe** [comment]
Closing, lack of activity.
