### ISSUE TITLE
`webapp` strategy seems to require a user session, even for API endpoints.

### ISSUE THREAD

**Issue by marijnvanderhorst** [auth0/laravel-auth0#336]
### SDK Version

Other (specify in 'additional context')

### PHP Version

PHP 8.1

### Composer Version

2.x

### What happened?

`webapp` strategy seems to require a user session, even for API endpoints.

We have a laravel application that uses both web and API routes. The web routes are stateful and require a user to be authenticated. The API routes are stateless and should only authorize requests based on the provided bearer tokens. This has always been working perfectly fine. However, with some recent update, this seems to have broken down completely.

We are using the `webapp` strategy since that would make the most sense to me. Is it documented somewhere how the behavior changes with the different strategies? The readme seems to require me to make a decision between stateful or stateless, but what if we need both? I would think that a "webapp" that can authenticate users can also authorize API requests, but apparently not.

When calling any API endpoint, we get an error `Session store not set on request.`. This seems to be caused by the `auth0.authorize` middleware relying on the `user()` within the auth guard, which in turn tries to retrieve the user from the session. This is, obviously, never going to work for any API endpoint.

Why use the strategy to determine where to retrieve the user from? Laravel has this very nice split in session-driven web routes and sessionless API routes, which is entirely thrown out of the window here. In my view, authorizing requests should always utilize the provided bearer token in the request, right? In which situation would we ever need the ID token in the session to *authorize* an action instead of using it for getting the authenticated user?

NB: this complete shift in behavior seems to be a breaking change and should have come as a major release when following semantic versioning. I did not expect a `composer update` to break our application when only the minor version was bumped.

### How can we reproduce this issue?

1. Create laravel application
2. Install this package
3. Configure it as `webapp`.
4. Add web route with session and authentication middleware.
5. Add API route without session but with `auth0.authorize:scope` middleware.
6. Call API endpoint and notice it relies on a user session even though it does not need it and could simply verify the bearer token that is provided in the request.

### Additional context

SDK version 7.3.0 broke everything. v7.0.1 was working fine.

**Comment by evansims** [comment]
Hi @marijnvanderhorst. 👋 Thanks for raising this issue, and I'm sorry to hear the issues you're facing on this.

I certainly understand and sympathize with your sentiments here. However, despite this previously working in your app, this was not an intended behavior and not how we've ever documented usage for the SDK to be implemented.

I can offer some background as to the decisions behind those changes, and why they're affecting your app in particular:

- The `Auth0\SDK\Configuration\SdkConfiguration::STRATEGY_REGULAR` strategy has always expressly required a session store. When one is not configured, the SDK will silently establish one for you. Until 7.2, a `CookieStore` instance was created by default. However, because cookies are not reliable with Laravel Octane usage, this was changed in 7.2 to now leverage Laravel Sessions.
  - Given that 7.2 now relies on Laravel's Sessions API, this change now raises an error in your app because it's expecting a configuration to be available for those sessions. This was still happening in prior versions, but silently because `CookieStore` is framework-agnostic and simply delivers raw cookies, so no configuration was necessary.
  - In either case, sessions being established on API routes could be potentially problematic for JSON responses in inadvertently delivering cookie headers. This is why we consider `STRATEGY_REGULAR` and `STRATEGY_API` to be mutually exclusive and separate for those use cases.
  - This issue surfaced within your app because of this change, but by all accounts, it is working as intended and as documented. We don't consider this a breaking change, but it is unfortunate for your app's implementation.

- As I'm sure you're already aware, but I'll say anyway for posterity’s sake for future GitHub searches, the `Auth0\SDK\Configuration\SdkConfiguration::STRATEGY_API` and `Auth0\SDK\Configuration\SdkConfiguration::STRATEGY_MANAGEMENT_API` strategies do not require a session store to be created.
  - Given that your app simultaneously handles both use cases that these strategies were intended to be mutually exclusive in handling, you are understandably between a rock and a hard place there in choosing strategies for your multipurpose app.

- An additional change in 7.2 was a bug-fix which unfortunately exacerbates the issue you're seeing: the Laravel SDK no longer permits both stateful and stateless configurations simultaneously out-of-the-box. The fact that this worked otherwise in the past was unintentional and not-as-documented. This would have allowed the behavior you rely on in your app, but we did not feel this was best practice as behavior from a security standpoint, and was otherwise never intentional.
  - Although this incidentally and unfortunately impacted your application, this was by all measures a bug-fix and not a breaking change, as it was never a feature. The Laravel SDK has always been pretty expressly documented as being an either-or configuration of stateless or stateful, and never intended to be used simultaneously for both.

All that said, we can definitely get a solution implemented for you:

First, I'd propose we implement a configuration toggle that allows you to opt in to overriding the default [exclusivity switch](https://github.com/auth0/laravel-auth0/blob/045a639b6ac75765b3de9dabc360eab8f6a4f2f7/src/Auth/Guard.php#L73) on stateful/stateless checks. I'm hesitant to add this to the `config\auth0.php` array itself, as this is intended to be handed off verbatim to the underlying PHP SDK, but I think a constant would make sense here. Something like `define('AUTH0_MULTISTATE_ENABLED')` being defined in the config, perhaps.

By itself, this is simple enough to do, but will still require you to have a Laravel Session configured and available if you are configuring your SDK as `Auth0\SDK\Configuration\SdkConfiguration::STRATEGY_REGULAR`. That's not an implementation detail we're willing to change, I'm afraid. It does not make sense to add a strategy specifically for this use case, as it is, as I mentioned, potentially problematic with regard to inadvertently delivering stateful cookies on API routes.

You could work around this within your application logic by listening for the `Auth0\Laravel\Event\Configuration\Built` event. This event passes the `Auth0\SDK\Configuration\SdkConfiguration` instance that's about to be used to instantiate the underlying SDK. In this, you could create your own `Auth0\SDK\Store\CookieStore` to use for the `sessionStorage` and `transientStorage`. This would effectively return your application to it's previously implemented behavior.

Another alternative we could consider is raising events within the various Middlewares for stateful authentication and stateless authorization, to allow your application to dynamically mutate it's SDK configuration to accommodate the request type as it happens (such as changing `strategy` to `STRATEGY_API`, or setting `sessionStorage` and `transientStorage` to a truly ephemeral storage interface, like `Auth0\SDK\Contract\StoreInterface\MemoryStore`.)

**Comment by evansims** [comment]
Hi @marijnvanderhorst, thanks — we appreciate your feedback!

As far as why this approach was adopted initially, I couldn't say — that was before my time with the company. At this point, however, it's what customers have expected and architected their applications around.

I do like your suggestion of offering two Guards, but we wouldn't be able to review that request until the next major release, which isn't current on our radar. I have backlogged it to review down the road, when we're able to take that on. This would also require some rethinking of the underlying PHP SDK to support.

In the meantime, I will work on implementing the options I suggested when the company returns from holiday (next week.)
