### ISSUE TITLE
Remove `final` from various class definitions

### ISSUE THREAD

**Issue by DimeZilla** [auth0/laravel-auth0#345]
### What should be added?

I humbly request that `final` be removed from a number of class definitions so that the classes are be made extendable by developers working on Laravel applications:

1) the `Auth0\Laravel\Store\LaravelSession` class definition: Since the session store is configurable via the `sessionStorage` key, I'd like to be able to extend the LaravelSession class so that I can alter specific pieces of behavior to the specifications of my Laravel application.

This relates to the issue filed in https://github.com/auth0/laravel-auth0/issues/344. If `final` was removed, it would be rather easy to extend the class and change how the session is retrieved.

2) All controllers defined in the `Auth0\Laravel\Http\Controller` namespace. Since we have to register these controllers in our routes/web files anyway, these should be extendable in case we want to extend and inject logic like checking if the user is in our local database or firing a custom event.

**Comment by evansims** [comment]
Hi @DimeZilla 👋 Thanks for raising this. I can certainly understand where you're coming from with your request, but we don't anticipate changing this. I'll try to avoid getting too long-winded with my explanation, but I do think offering context is important.

Our use of `final` is an intentional design decision of our API classes, and one that was not taken lightly. But to put it simply, we don't want developers to extend those classes directly. Allowing these to be extended leads to API pollution and logic conflicts, and all too often a minor changes to the SDK becomes a breaking change for downstream applications in completely unnecessary ways.

Eventually, we do plan to offer abstract classes that will offer a compromise on this, while ensuring the SDK integrity, security and reliability. But I know that doesn't help you right now, and I apologize. For now, the expectation as that you use these classes as-they-are and build application logic around them, or plug in your own classes as necessary that replicate the base functionality.

Although I know it's a little inconvenient, this design decision isn't really limiting. All the underlying API methods are still available for you to leverage in your application code. We support extensibility through a number of Interfaces that can add custom persistent data stores, caching interfaces, and so forth. We also offer numerous event hooks that you can listen for to augment the SDK behavior safely. And of course, all (or nearly all) of our classes provide interfaces that you can mock for unit testing purposes.

Not the answer you were looking for, I know, and I'm sorry to have to disappoint — however, I do feel strongly about this being the right decision for the SDK.

**Comment by DimeZilla** [comment]
Sounds good! Thanks for the write-up and the clear explanations.
