### ISSUE TITLE
Update for Laravel 10

### ISSUE THREAD

**Issue by devjack** [auth0/laravel-auth0#347]
### What should be added?

👋 Hiya folks!

Couldn't find any issues, PR's or other commentary around this - so opening this issue to prompt/track future support for Laravel 10. 🤞 

Relevant links:
 - Official Upgrade Guide: https://laravel.com/docs/10.x/upgrade
 - Shift might automate a bunch of this for you: https://laravelshift.com/

**Comment by evansims** [comment]
Hi @devjack 👋 Thanks. Development is already underway with a forthcoming update that adds expanded Laravel 10 support. Should be released in a week or two.

**Comment by devjack** [comment]
Thats great news, thanks for the update @evansims. I can even see progress being made on `main`  🎉 

Is closing issues that have planned PR's standard practice in the auth0 org?  As an outsider to that process it feels like it would be nice to have this issue open until resolved so that notifications can let us (collectively) know when support is merged.  Otherwise its difficult to know when updates are made, outside of coming back and checking.

**Comment by l4nos** [comment]
Why has this issue been closed? I'm unable to install it.

You clearly have illuminate/support in your require, which makes it incompatible with laravel 10 or higher as  illuminate/support cannot exist along with it.

**Comment by evansims** [comment]
@l4nos The SDK has had Laravel 10 support since 7.5, released in April 2023. We also presently support Laravel 11.

I'm not sure why you're under the impression `laravel/support` is incompatible, but you are mistaken. It's supported by Laravel [9](https://packagist.org/packages/illuminate/support#9.x-dev), [10](https://packagist.org/packages/illuminate/support#10.x-dev), [11](https://packagist.org/packages/illuminate/support#11.x-dev), and will presumably continue to supported indefinitely onward.

It's the API that adds support for Facades, among other things.

It can be installed alongside Laravel without issue and is bundled with Laravel itself — including Laravel 10. Its incorporation in this SDK is to enable the interfaces it exposes to be used and extended by the packages. Completely standard stuff.

If you're having issues with the SDK, it isn't because of `illuminate/support` being a dependency of the SDK. Please create a new thread, as there's no sense in disturbing others who participated in this thread over a year ago.
