### ISSUE TITLE
\Auth::login() not accepting a User

### ISSUE THREAD

**Issue by watercayman** [auth0/laravel-auth0#358]
### SDK Version

7.5.1

### PHP Version

PHP 8.2

### Composer Version

2.x

### What happened?

Within our seeders and kernel commands, we have various places where we need to log in a Laravel user in order to accomplish tasks that a user has permission to do, or set a specific element against that user as if they were logged in.  This has worked without issue using the standard Laravel `login()` method, until updating to V7.5.  The login function appears to have been changed and no longer accepts a User object per Laravel default.

This is consistently failing across all of our applications now.  I imagine it will have issues across other packages that employ a Login-as function as well.  (Unless I'm doing something wrong?)

### How can we reproduce this issue?

Add a simple login statement in a Laravel app:

    \Auth::login(User::find(1));

Will fail with the following message:

    Auth0\Laravel\Auth\Guard::login(): Argument #1 ($credential) must be of type ?Auth0\Laravel\Contract\Entities\Credential, App\Models\User given

**Comment by evansims** [comment]
Hi @watercayman 👋 Thanks for your question. I'm sorry to hear you're hitting some challenges with this.

That's a curious situation. Laravel does not have any interface definition for `login()` on the Guards API that would define any method signature expectations. [You can reference the interface definition here.](https://laravel.com/api/10.x/Illuminate/Contracts/Auth/Guard.html) As there's no default usage implied or method signature defined by an interface, it's an awfully risky game for other packages to be invoking methods blindly.

That said, `setUser()` is available and defined by the `Illuminate\Contracts\Auth\Guard` interface to assign a user for the current request context. I can't speak to other packages or why they would use `login()` instead of `setUser()`, but by all accounts that is the method they should be calling.

**Comment by watercayman** [comment]
Hi @evansims, really appreciate the prompt response.  I can confirm that `setUser()` is a successful work-around in our use-cases against `login()`.  We'll go through and refactor the rest of the apps, but I believe this will work for us.  `setUser()` is at least as functional, and in fact may even be more proper, as you note.  

Some of these apps have been through various iterations of Laravel (and Auth0), and some were originally using the Laravel auth scaffold.  To my limited understanding (at the time certainly), Auth and the logged in user were a little closer in my mind.  If we're using Auth0 for Auth... i can see where that [login() ](https://laravel.com/docs/10.x/authentication#other-authentication-methods)method may be obsolete.  Just an observation - I am always a little weary when a package removes the native function of the base framework... but I think I'm beyond the scope of my understanding to argue one way or the other here.

For us, I think we're good, and I thank you once again for the suggestion to use `setUser()`.

**Comment by watercayman** [comment]
Well shoot.  Sorry about re-opening, but this issue may be related to the user object failing in Web Tinker.  Not sure if I should open a new issue, or dump this here, apologies.

I am unable to open Spatie's Web Tinker using SDK V7.5.  Tinker is ubiquitous in Laravel, so I assume this will be an issue for most users (if indeed the issue is with Auth).

If I open myAppUrl/tinker as usual, I now get a 403 Forbidden error on every attempt.  This is while logged in with an authenticated user.  I have tested on several browsers with different states, all failed.  This never failed before with an auth user logged in.

I dug down into the Vendor code and was able to successfully gain access by altering the vendor code (as a test) by manually setting the user in Spatie's **Authorize** middleware: 
 
     protected function allowedToUseTinker(): bool
      {
        if (! config('web-tinker.enabled')) {
            return false;
        }
        \Auth::setUser(\App\Models\User::find(2));  // <--- HERE
        
        return Gate::check('viewWebTinker');
      } 

Adding the user allowed the Tinker page to load and function.  Without it, dumping the user at this point yielded `null`, which I have to assume is the problem.  I don't know where the package is hunting for the user, but it is no longer finding it.  Or finding the right type of object perhaps.

This is a showstopper as this package is used every day (by most Laravel devs).  But I am concerned that if the change made to the Auth user object is indeed the culprit, that it is going to affect other packages.  Thinking this through, L10 has been out for 2 months, and checking Spatie's issues, there are not problems reported from the update.  Thus, I think this may be an issue from the SDK?

@evansims if you could please take a look at this, I would be grateful.  If I can help provide more information, I'm happy to help if I can.

**Comment by evansims** [comment]
Hi @watercayman 👋 Sorry you're still hitting issues there.

> If we're using Auth0 for Auth... i can see where that [login() ](https://laravel.com/docs/10.x/authentication#other-authentication-methods)method may be obsolete.
> Just an observation - I am always a little weary when a package removes the native function of the base framework... but I think I'm beyond the scope of my understanding to argue one way or the other here.

I apologize for any confusion — `login()` is neither obsolete nor has it been removed; its purpose is simply different in this SDK from Laravel's own auth middleware.

To clarify, `login()` is not a native function of Laravel, or it's Guard API, at all. You can reference the Interface specification here: https://laravel.com/api/10.x/Illuminate/Contracts/Auth/Authenticatable.html It is not part of any base framework contract.

I understand where you are coming from in this confusion because they demonstrate it within their documentation — but this is a demonstration of their own authentication middleware, and not a declarative statement on any API that all middleware use.

By all accounts, the method could just as easily not exist within the SDK at all, and it would still be a perfectly valid Guard to use with Laravel.

> I am unable to open Spatie's Web Tinker using SDK V7.5. Tinker is ubiquitous in Laravel, so I assume this will be an issue for most users (if indeed the issue is with Auth).

As a Laravel developer myself since version 4, I would have to disagree with your assessment that such a third-party package is at all ubiquitous. I have never encountered Web Tinker, or had it mentioned to me, before now. (I have a great deal of respect for Spatie and their packages, and what they do for the Laravel community at large. I'm a regular licensee of their apps and courses. I don't mean to sound negative about them. I love what they do.)

> I dug down into the Vendor code and was able to successfully gain access by altering the vendor code (as a test) by manually setting the user in Spatie's Authorize middleware:

At a glance, it seems like the problem you're having is that Web Tinker [injects its own authentication middleware](https://github.com/spatie/laravel-web-tinker) that makes calls to the Laravel Gate API. Gate is an authorization API that allows access to endpoints based on user permissions, [but it does not deal with authentication.](https://auth0.com/docs/get-started/identity-fundamentals/authentication-and-authorization)

The Gate API layer is not supported by the SDK at this time, although that is definitely on our roadmap for a future feature addition.

**Comment by watercayman** [comment]
Thanks for the response @evansims.  

Interesting, and certainly confusing about `login()`.  It seemed like the way to go based on their docs, but I can certainly see where you are coming from in terms of the interaction via API.  To me, an end user, I would not dig that deep to know this - I only see it working in one version and then not working in the next.  However, your suggestion to use `setUser()` is a viable and better / more clear solution.

Sorry I've got two items in this one ticket - I thought they might have been connected.  And yes, you are correct -- if you haven't been using the Web version of Tinker, it is clearly not ubiquitous.  You should definitely check it out, it is a fantastic package.  

I've got a hackish middleware that can get this working until the fix is in place.  However, should this be a concern for you that something changed to stop this from working in this newest version of the SDK, and may it reflect in other packages if they are doing the same thing as Spatie?  I understand the Gate API is not supported by the SDK, but was it previously?  IE I guess I would ask why did this suddenly stop working; Tinker has worked with all prior versions of the SDK.
