### ISSUE TITLE
Bug: Relax middleware response type hinting to permit broader and custom response types.

### ISSUE THREAD

**Issue by Bntb2012** [auth0/laravel-auth0#359]
### SDK Version

7.5

### PHP Version

PHP 8.2

### Composer Version

2.x

### What happened?

Having problems with all auth that is not directly on the page.  

- Uploading an image via a tinyMCE editor through its standard upload function results in this error:
- `Auth0\Laravel\Http\Middleware\Stateful\Authenticate::handle()::handle(): Return value must be of type Illuminate\Http\Response|Illuminate\Http\RedirectResponse|Illuminate\Http\JsonResponse|Illuminate\Routing\Redirector, Symfony\Component\HttpFoundation\JsonResponse returned {"userId":2,"exception":"[object] (TypeError(code: 0):`
- Attempting to send a page to PDF results in this similar error:
- `Auth0\Laravel\Http\Middleware\Stateful\Authenticate::handle(): Return value must be of type Illuminate\Http\Response|Illuminate\Http\RedirectResponse|Illuminate\Http\JsonResponse|Illuminate\Routing\Redirector, Symfony\Component\HttpFoundation\BinaryFileResponse returned`
- Confirming the error on not being able to authenticate into Laravel Tinker (noted [here](https://github.com/auth0/laravel-auth0/issues/358)):
- `403 Forbidden`

Please note, all of these have worked without error for years.  This represents a significant part of our code; we cannot refactor all of this.  I don't have a good understanding of why all this is now broken, but it seems something major has changed in how Auth0 is handling the user or at least the middleware?

### How can we reproduce this issue?

Try opening a Tinker page for the easiest one

### Additional context

We can't upgrade to Laravel 10 at this point.  Please help to resolve.

**Comment by Bntb2012** [comment]
Additional failure - we are unable to download files using SDK 7.5.1: 

`App\Http\Middleware\AuthenticateAuth0Custom::handle(): Return value must be of type Illuminate\Http\Response|Illuminate\Http\RedirectResponse|Illuminate\Http\JsonResponse|Illuminate\Routing\Redirector, Symfony\Component\HttpFoundation\StreamedResponse returned`

**Comment by evansims** [comment]
Hi @Bntb2012 👋 Laravel 10 expects the `handle()` method for middleware to return a distinct Response object, or some variation of one, so the SDK's type hinting for the method was updated to support that. I'm sorry to hear that this change is causing issues for you.

Regarding your first comment, it appears something within your application is sending a `Symfony\Component\HttpFoundation\JsonResponse` response object through the middleware stack, instead of `Illuminate\Http\JsonResponse`.

Thankfully, this is an easy enough fix from the SDK side, as we can just relax the type hint from the middleware to expect returning `Symfony\Component\HttpFoundation\Response`, instead of some variant of `Illuminate\Http\Response` — as `Illuminate\Http\Response` itself extends `Symfony\Component\HttpFoundation\Response` anyway.

With regard to your second comment, this would be because, for some reason, [the Laravel ResponseFactory](https://github.com/laravel/framework/blob/10.x/src/Illuminate/Routing/ResponseFactory.php) returns `Symfony\Component\HttpFoundation\BinaryFileResponse` or `Symfony\Component\HttpFoundation\StreamedResponse` for downloads. Odd that it doesn't extend a native type from `Illuminate\Http\JsonResponse`, but it is what it is.

In any case, the fix is the same for both of your comments here. Let me commit a fix to `main` and you can give it a try and see if that fixes things for you, but it should cover all the bases.

**Comment by evansims** [comment]
I've updated the `main` development branch with some fixes which should resolve the issue for you. Can you please test these changes and let me know if it works for you? Thanks!

**Comment by Bntb2012** [comment]
Hi @evansims, 

Yes, of course, the type hints makes perfect sense.  I pulled the dev-main and can confirm all of the return type errors are gone.  All downloads, tinyMCE uploads, and PDF printing seem to be working fine.  The relaxing of the type hint looks like a **good solve**.  

Also confirming that Tinker is still **not** working with either 7.5 or dev-main.  Works fine with all previous versions.

Many thanks for the update and the quick solve for the return issue!

**Comment by evansims** [comment]
Hey @Bntb2012 👋 Thanks for checking on that! I've just released 7.5.2, which packages those changes to resolve the issue. 👍
