### ISSUE TITLE
Getting "Auth driver [auth0] for guard [auth0] is not defined." after upgrading from 7.4.0 to 7.5.2

### ISSUE THREAD

**Issue by uandco** [auth0/laravel-auth0#361]
### Laravel Version

Laravel 9.x

### SDK Version

SDK 7.5

### PHP Version

PHP 8.1

### What happened?

Ran `composer update` to upgrade from 7.4 to 7.5.2.

Application breaks with `Auth driver [auth0] for guard [auth0] is not defined.` as soon as `Auth::user()` is called.

I tried the `legacyGuardUserMethod` config option to no avail.

### How can we reproduce this issue?

Run `composer update` on working app using SDK 7.4.

**Comment by evansims** [comment]
Hi @uandco 👋 Sorry for the trouble on this, but to adopt support for Laravel 10, we found we could no longer use the same string for both the guard and the provider due to changes in the singleton factory. This is called out in [the CHANGELOG](https://github.com/auth0/laravel-auth0/blob/main/CHANGELOG.md#750-2023-04-03) and [GitHub release notes](https://github.com/auth0/laravel-auth0/releases/tag/7.5.0), and you can find a demonstration of the new configuration in [the README](https://github.com/auth0/laravel-auth0#configuring-your-application). Simply change the Guard driver to `auth0.driver` and Provider driver to `auth0.provider` in your `config/auth.php` to resolve the issue.

**Comment by uandco** [comment]
Thanks @evansims , maybe you should make it clearer this is valid for both Laravel 10 and 9. Also the guide on auth0.com still shows the old “auth0” aliases, with no mention of that change

**Comment by lunfel** [comment]
I jumped from 7.4 to 7.11 and these are the changes I needed to do to make it work:

7.11
```
'guards' => [
    'auth0' => [
        'driver' => 'auth0.guard',
        'provider' => 'auth0.provider'
    ],
],
'providers' => [
    'auth0' => [
        'driver' => 'auth0.driver',
    ],
],
```
7.4
```
'guards' => [
    'auth0' => [
        'driver' => 'auth0',
        'provider' => 'auth0'
    ],
],
'providers' => [
    'auth0' => [
        'driver' => 'auth0',
    ],
],
```
