### ISSUE TITLE
Behaviour of `Auth::login` combined with `Request::create` (possible improvement suggestion)

### ISSUE THREAD

**Issue by uandco** [auth0/laravel-auth0#369]
### Laravel Version

Laravel 9.x

### SDK Version

SDK 7.6

### PHP Version

PHP 8.1

### What happened?

With SDK version 7.4, the `auth` middleware could be used instead of `auth0.authenticate`.

From an artisan command, one could  do `Request::create('/some-auth-middleware-protected-route/')` after `Auth::login($user)` and the request worked as intended, with a valid session.

With SDK 7.6, when using the `auth0.authenticate` middleware and after adapting to `Auth::login(Credential::create($user))`, `Request::create`'s output is a redirect to the login route, so I believe the session is not available in the newly created request.

Do you plan on implementing a similar behaviour?
If not, what's the best way to achieve this?

Thanks

### How can we reproduce this issue?

See above

**Comment by evansims** [comment]
Hey, @uandco 👋 Thanks for your question!

You raise a perfectly valid point, and it's an unfortunate side effect of leaning on the middleware to gate authentication/authorization — the guard can't, by itself (after 7.5), resolve user states, which makes it somewhat limited for use with the `auth` middleware.

The fact that this worked prior to 7.5 was not really an intentional design, and could potentially lead to some unexpected behavior, which is why it was changed. Both approaches have trade-offs, to be quite honest.

For now, we don't expect to change this behavior, but our roadmap for the next major is to introduce two, distinct Guard types: one for authentication, and the other for authorization. Within each of these guards, we'll move most (potentially all) the behavior that's currently handled by the router middleware directly into the guards themselves. This change is not destined for the near term, however, and relies on a new major of the underlying PHP SDK this Laravel SDK is built upon to really support that functionality. (There are somewhat complicated technical reasons why it isn't possible at the moment.)

You should be able to use the [legacyGuardUserMethod](https://github.com/auth0/laravel-auth0/blob/main/CHANGELOG.md#changes-to-user-behavior) feature to make the Guard behave the way you're looking for in the meantime, but I can't promise that to be the case as I've not had a chance to try it myself. Also, if you don't want to redirect unauthenticated requests to the login route, make sure you're using the `auth0.authenticate.optional` middleware, as it's designed not to do that.

**Comment by uandco** [comment]
Thanks for your answer @evansims , I tried with our without `legacyGuardUserMethod` but that doesn't help, I can never get a valid session when using `Request::create`.

To add a bit of context, I'm using this with Laravel Nova, combined with an artisan task that combines all the CSS and JS from the different Nova components (this needs a Nova instance to be instantiated to access the `Nova::allScripts()` and `Nova::allStyles()` methods, hence the `Request::create()`, see https://github.com/laravel/nova-issues/issues/1146#issuecomment-515891323

It's a bit tricky because my main Nova route has to be authenticated and I thought `auth0.authenticate.optional` was not an option, but adding an extra middleware after `auth0.authenticate.optional`, redirecting to `/` if `Auth::user()` is null, solves the issue. It still makes authentication mandatory but it passes the guard between the 2 middlewares, which is enough to instantiate Nova and give access to the methods I need.

I'm documenting this mostly for others who would run the same kind of setup ;-)
