### ISSUE TITLE
Auth0::getUser() returns null even when Auth::check() is true

### ISSUE THREAD

**Issue by OscarOrSomething** [auth0/laravel-auth0#38]
Basically:

```

Route::get('/api/protected', array('middleware' => 'auth0.jwt', function() {
    echo json_encode(Auth::check())."\n";
    echo json_encode(Auth0::jwtUser())."\n";

    echo json_encode(Auth0::getUser())."\n";
}));
```

returns 

```
true
{"iss":"https:\/\/***.eu.auth0.com\/","sub":"***","aud":"***","exp":***,"iat":***}
null
```

with 

`Authorization: Bearer e****`

**Comment by OscarOrSomething** [comment]
bump?

**Comment by glena** [comment]
You should use `Auth0::jwtUser()` to get the content of the jwt or `Auth::user()` to get the user. If you need other user attributes as the token claims, check [this doc](https://auth0.com/docs/scopes).

`Auth0::getUser()` is used on the oauth2 flow, not for jwt (I see now it might be confusing).

**Comment by OscarOrSomething** [comment]
`Auth::user()` returns the same as Auth0::jwtUser() for me, Just to be clear I'd like to get the roles of the user to check if they're allowed to do certain things

```
Route::get('/api/protected', array('middleware' => 'auth0.jwt', function() {
    echo json_encode(Auth::check())."\n";
    echo json_encode(Auth0::jwtUser())."\n";

    dd(Auth::user());
}));
```

/api/protected
```
true {"iss":"","sub":"","aud":"","exp","iat"}
Auth0JWTUser {#178
  -userInfo: array:5 [
    "iss" => ""
    "sub" => ""
    "aud" => ""
    "exp" => 
    "iat" => 
  ]
}
```

**Comment by glena** [comment]
Yes, by default both with give you the token content.

In the case of `Auth::user()` with return the User object, you can use the user repository to change this behaviour (for example, call the auth0 API to get the entire user -not recommended because it will add extra latency to the request-, or get info from your database).

If you want to add extra info to the token (I think this is what you are trying to do) check this doc https://auth0.com/docs/scopes . You need to add the scopes you want when you authenticate the use and this info will be added as token claims. In the case of metadata, if you the user_metadata or app_metadata scope, the entire object will be added (cant ask for sub properties). If you want to return only one metadata property, you can use a rule like this one to customize it https://github.com/auth0/rules/blob/master/rules/custom-scopes.md

**Comment by OscarOrSomething** [comment]
Thanks, Kinda new to the JWT thing.

**Comment by glena** [comment]
Np :)
