### ISSUE TITLE
SDK hitting database many times for user

### ISSUE THREAD

**Issue by watercayman** [auth0/laravel-auth0#418]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

7.5+

### PHP Version

PHP 8.2

### Description

When we moved to version 7.5 & L10, we suddenly saw an increase in the number of database hits increase by a large amount.  A common increase would be from 3 on a page to 120, with 115 duplicate queries.

The dupe queries were essentially get user and get roles.  We are using a **CustomUserRepository** (CUR) to get the user from session and then use our database to pull/create/manage users.  This worked very well with the <7.0 **Auth0IndexController**, and still worked after the refactor to the CUR in 7.0.  Our CUR is simple and follows the example from @evansims fairly closely (with a bit of extra stuff after we grab the user).

I don't know if Auth0 Laravel SDK changed or Laravel 10 changed the way the path is now bouncing into auth on the CUR -- sometimes hundreds of times -- but I do know it did _not_ happen prior to 7.5.  This is a significant hit to performance, so I started to see what we might be missing.  `auth0_session_user` is sitting in session on every user, but I can't see what sets this.  Perhaps the PHP SDK?  I note the quickstart mentions adding the user to cache in order to prevent many hits to Auth0 (or in our case to the DB), so I thought I'd try to use the existing session data and build the Laravel User object.  But I don't think this is possible b/c the session provided is an array - I don't think it is simple to efficiently add the relationship roles from the array.

So I created similar logic by adding the user to the session via the Laravel object.  Here is the basic code within `fromSession`:

```
           if(session()->has('auth_user'))                 // new
                return session()->get('auth_user');    // new

            $appUser = User::firstOrCreate([
                'email' => $user['email']], [
                'sub' => $user['sub'],
                'name' => $user['email']]);

           // more stuff

            session()->put('auth_user', $appUser);   // new
            
            return $appUser;
```
This seems to work fine - I'm back down to a few DB hits and much faster.  I have a few questions though, please:

- Any idea why this changed?
- Is this object in session an acceptable / proper way to do this?  I am guessing so, as the original Auth0 session var seems to be intended to do very similar?
- If this is correct, is there a way to remove all the extra session auth0 stuff (seems a waste to duplicate the info in an array and object, plus I don't think I'm using the other auth0_xxx session vars).  Alternatively - is there a way to add as an object instead?
- I did set the persistence on the config file to false on all items, but this doesn't seem to be connected to the vars?  I can't seem to get rid of them, though I'm not sure they are still necessary.

Apologies if this is something obvious, but I can't find the reason for the change, so hoping I'm heading in the right direction.  Appreciate any insight!

### How can we reproduce this issue?

Use a Custom repo and draw user from database without any special call / put to the session.

**Comment by PxtServices** [comment]
Wow.  We look at our pages and see some over 100 duplicate queries.  Queries like select user and select roles on this user.  We also use custom user repository and manage user on our database.

This was no problem for us before we move to 7.5 for sure.

We used @watercayman fix and this fixes all those duplicates.  

His/her third question is maybe better fix?  If the array is carry exactly the same info, can the Laravel SDK add config to make this user object instead?  Something like `session_auth_is_object`, and default no.  This seems to be intent of original array, but can't use it on Laravel.  So don't need this in memory for Laravel SDK maybe?

**Comment by evansims** [comment]
Hey, @watercayman 👋 Thanks for your question

> Any idea why this changed?

We recently refactored the library to more reliably synchronize the session state between the Laravel session and the underlying PHP SDK's state management engine. That change most likely introduced more calls.

> Is this object in session an acceptable / proper way to do this? I am guessing so, as the original Auth0 session var seems to be intended to do very similar?

Yep! That looks like a perfectly reasonable approach toward reducing database calls to me. I don't see any problem with that.

Alternatively, you might consider using a cache for the user object rather than storing it on the session, using the session id as the cache key. I'm honestly not sure if you risk possibly hitting session storage limitations by storing the object there — might not be an issue, but I think using a cache might be a slightly more optimal approach. Either way works, though.

> If this is correct, is there a way to remove all the extra session auth0 stuff (seems a waste to duplicate the info in an array and object, plus I don't think I'm using the other auth0_xxx session vars). Alternatively - is there a way to add as an object instead?

There is no good way to do that at present; sorry. I'll certainly think about this suggestion and see what I can do for a future release, though.

> I did set the persistence on the config file to false on all items, but this doesn't seem to be connected to the vars? I can't seem to get rid of them, though I'm not sure they are still necessary.

If I understand correctly, I think you're referring to the various persist configuration options of the underling PHP SDK, that the Laravel SDK inherits? If so, that's correct, those particular configuration options are ignored for the Laravel SDK as they're necessary to facilitate the authentication state in our current integration. I have some ideas on how we can improve on this in the future, but that has to wait for the next major of the PHP SDK to build the framework for that.

**Comment by evansims** [comment]
Hi @PxtServices 👋

> Wow. We look at our pages and see some over 100 duplicate queries. Queries like select user and select roles on this user. We also use custom user repository and manage user on our database.
> This was no problem for us before we move to 7.5 for sure.

Although the issue may have been less prevalent due to the way the previous versions worked, the underlying scenario would actually still be there, albeit less noisy. Caching should be used with custom user repositories to avoid unnecessary redundant lookups, particularly if you decide to implement user storage in a database.

Sorry for any challenges introduced by this change, but believe it or not, these changes ultimately lead to a more reliable session storage mechanism — this is just an unfortunate side effect of the change. We'll update the custom user repository example/documentation for better clarity on all this.

> His/her third question is maybe better fix? If the array is carry exactly the same info, can the Laravel SDK add config to make this user object instead? Something like session_auth_is_object, and default no. This seems to be intent of original array, but can't use it on Laravel. So don't need this in memory for Laravel SDK maybe?

Right now this isn't really possible, but I'll see what I can do to include something like this in a future release.
