### ISSUE TITLE
Fresh Installation - The JWT string must contain two dots

### ISSUE THREAD

**Issue by andrewlindemulder** [auth0/laravel-auth0#429]
### Checklist

- [X] This can be reproduced using [the quickstart sample application](https://github.com/auth0-samples/laravel).
- [X] I have looked at [the README](https://github.com/auth0/laravel-auth0/#readme) and have not found a solution.
- [X] I have looked at [the `docs` directory](https://github.com/auth0/laravel-auth0/blob/main/docs) and have not found a solution.
- [X] I have searched [previous issues](https://github.com/auth0/laravel-auth0/issues) and have not found a solution.
- [X] I have searched [the Auth0 Community](https://community.auth0.com/tag/laravel) and have not found a solution.
- [X] I agree to uphold [the Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Laravel Version

10

### SDK Version

Other (specify below)

### PHP Version

PHP 8.2

### Description

When isntalling the Auth0 SDK I get this error when following the guide at the API creation step.

`An unexpected error occurred while attempting to create an API with name 'My Laravel Application API' and identifier 'https://github.com/auth0/laravel-auth0': 409 Conflict: A resource server already exists with identifer https://github.com/auth0/laravel-auth0`

When trying to auth I initially get the "Invalid State" error. after visiting /logout i am then presented with this error:
`The JWT string must contain two dots`

This is a fresh installation of Laravel and Auth0-SDK. tried on both Laravel 9 and 10 and the Auth0-SDK 7.9 and 7.10.

### How can we reproduce this issue?

follow the guide. errors happen on every install/run.

**Comment by evansims** [comment]
Hi @andrewlindemulder 👋

If you're receiving an error stating `An unexpected error occurred while attempting to create an API with name 'My Laravel Application API' and identifier 'https://github.com/auth0/laravel-auth0': 409 Conflict: A resource server already exists with identifer https://github.com/auth0/laravel-auth0` then you may have mistakenly created the API twice. You can go to your Auth0 dashboard and deleted the previous/redundant API.

In regards to `The JWT string must contain two dots`, this means the API key you've provided the SDK is not valid. Is it possible you have mistakenly passed an ID token rather than an access token as expected?

**Comment by rasmustaarnby** [comment]
Hi @andrewlindemulder 

Not sure if you have found the solution based on @evansims answer but I stumbled upon this issue here while experiencing the same "error". 

While it's mentioned as a step in the quick start guide, I failed to take notice when running through it and thus missed the step. 

In the Auth0 admin you need to setup both an application and api. You then need to include the identifier of that API along with the other creds in the .env or wherever you define it. 
If you don't do that you'll get an **opaque access token** back from Auth0. 

```
AUTH0_DOMAIN=...
AUTH0_CLIENT_ID=...
AUTH0_CLIENT_SECRET=...
AUTH0_AUDIENCE="API Identifier goes here" <-- this is what you're missing
```
See https://github.com/auth0-samples/laravel/blob/7.x/sample/.env.example#L61-L64


You can find more info here:

- https://community.auth0.com/t/jwt-verifier-exception-com-auth0-jwt-exceptions-jwtdecodeexception-the-token-was-expected-to-have-3-parts-but-got-5/98398 
- https://auth0.com/docs/secure/tokens/access-tokens#custom-api-access-tokens
- https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens#parameters
