### ISSUE TITLE
OnLogin callback question

### ISSUE THREAD

**Issue by tomwurzbach** [auth0/laravel-auth0#97]
Great and straightforward library -- thanks.  Q re: callback:

The Auth0Service exposes three functions in support of a callback on login (called by the Auth0Controller). When does an application call onLogin to set up the callback? Do you typically see it in the boot section of the AuthServiceProvider or LoginServiceProvider?  I can't come up with a way that doesn't seem like a kludge.  

Thank you.

**Comment by joshcanhelp** [comment]
@tomwurzbach - glad it's helpful and thank you for the feedback! Sorry for the delayed response here, I didn't get/see the notification. 

I guess my main question is ... is this a part of custom functionality or are you just looking to get up and running? Our [quickstart guide](https://auth0.com/docs/quickstart/webapp/laravel) walks you through how to get everything wired up and start processing logins. 

If you want to do additional processing on login, which it sounds like you do, my inclination is to put that in `app/Providers/AuthServiceProvider.php` rather than `vendor/auth0/login/src/Auth0/Login/LoginServiceProvider.php` since anything in the `vendor` folder will get over-written with an update. You could change `config/app.php` to point to a custom provider but then you wouldn't be getting any updates made to `LoginServiceProvider.php`.

I think this could definitely benefit from an example in this repo ... happy to accept a PR if you come up with something you like or will assign it to myself and handle as soon as I'm able.

Thanks!

**Comment by jamesmehorter** [comment]
I also needed to run some custom code after a user successfully logged in. My solution was to update the Auth0Service instance in the Laravel IoC so that it calls my callback after logging the user in.

I added the following to `Providers\AuthServiceProvider.php:boot()` but I'm sure it could go elsewhere, and/or call a class/method instead of a closure (this was just my dummy proof-of-concept)

```
$this->app->extend(\Auth0\LoginAuth0Service::class, function ($service, $app) {
    $service->onLogin(function ($user) {
        print_r($user);
        // add custom logic here
    });

    return $service;
});
```

**Comment by jamesmehorter** [comment]
FYI, there seems to be a bit of a bug in the Auth0 package around this functionality. The onLogin callback allows returning the $user, I would presume this is meant to allow updating the user object which is stored in the SessionGuard. However, the Auth0 service calls the Auth0 SDK's setUser() BEFORE calling the onLogin callback. Just know that the $user in the onLogin callback cannot be updated. This is essentially ONLY an "event" which you can subscribe to.

**Comment by evansims** [comment]
Thanks @jamesmehorter! Solid suggestion there, I agree that allowing the user to be updated from the callback makes perfect sense. I'll try to get a PR open to add that yet this week, or if you have a moment to open one before then feel free!
